export default {
  anatomy: [
    {
      modelTitle: 'Cirozna jetra',
      modelLogo: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 2,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/model1/cirozna_jetra/a_ciroznajetra.gltf'),
      modelResourcesArr: [
        require('../models/anatomy/model1/cirozna_jetra/ciroznajetra.bin'),
        require('../models/anatomy/model1/cirozna_jetra/material_0_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Mozak',
      modelLogo: require('../assets/modelImages/anatomy/model2/mozakL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0025,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/model2/mozak/a_mozak.gltf'),
      modelResourcesArr: [
        require('../models/anatomy/model2/mozak/mozak.bin'),
        require('../models/anatomy/model2/mozak/mat0_0_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_1_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_2_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_3_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_4_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_5_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_6_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_7_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_8_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_9_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_10_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_11_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_12_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_13_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_14_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_15_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_16_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_17_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_18_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_19_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_20_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_22_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_23_baseColor.jpg'),
        require('../models/anatomy/model2/mozak/mat0_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Srčana mana',
      modelLogo: require('../assets/modelImages/anatomy/model3/srcanamanaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/model3/srcana_mana/a_srcanamana.gltf'),
      modelResourcesArr: [
        require('../models/anatomy/model3/srcana_mana/srcanamana.bin'),
        require('../models/anatomy/model3/srcana_mana/Left_atrium_baseColor.png'),
        require('../models/anatomy/model3/srcana_mana/Left_atrium_metallicRoughness.png'),
        require('../models/anatomy/model3/srcana_mana/Left_atrium_normal.png'),
        require('../models/anatomy/model3/srcana_mana/Right_atrium_baseColor.png'),
        require('../models/anatomy/model3/srcana_mana/Right_atrium_metallicRoughness.png'),
        require('../models/anatomy/model3/srcana_mana/Right_atrium_normal.png'),
        require('../models/anatomy/model3/srcana_mana/Ventricles_baseColor.png'),
        require('../models/anatomy/model3/srcana_mana/Ventricles_metallicRoughness.png'),
        require('../models/anatomy/model3/srcana_mana/Ventricles_normal.png'),
      ],
      modelPositionArray: [0, -0.9, -0.5],
    },
    {
      modelTitle: 'Bubreg',
      modelLogo: require('../assets/modelImages/anatomy/model4/bubregL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 1.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/model4/bubreg/a_bubreg.gltf'),
      modelResourcesArr: [
        require('../models/anatomy/model4/bubreg/bubreg.bin'),
        require('../models/anatomy/model4/bubreg/Njure_grundmaterial_baseColor.png'),
        require('../models/anatomy/model4/bubreg/Njure_grundmaterial_normal.png'),
      ],
      modelRotationArray: [90, 45, 0],
    },
  ],
  astronomy: [
    {
      modelTitle: 'Mjesec',
      modelLogo: require('../assets/modelImages/astronomy/model1/mjesecL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0001,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/astronomy/model1/mjesec/a_mjesec.gltf'),
      modelResourcesArr: [
        require('../models/astronomy/model1/mjesec/mjesec.bin'),
        require('../models/astronomy/model1/mjesec/Material_u1_v1_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Mars',
      modelLogo: require('../assets/modelImages/astronomy/model2/marsL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/astronomy/model2/mars/a_mars.gltf'),
      modelResourcesArr: [
        require('../models/astronomy/model2/mars/mars.bin'),
        require('../models/astronomy/model2/mars/moon_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Sputnjik 1',
      modelLogo: require('../assets/modelImages/astronomy/model3/sputnik1L.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.15,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/astronomy/model3/sputnik1/a_sputnik.gltf'),
      modelResourcesArr: [
        require('../models/astronomy/model3/sputnik1/sputnik.bin'),
        require('../models/astronomy/model3/sputnik1/Material1_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Zemlja',
      modelLogo: require('../assets/modelImages/astronomy/model4/zemljaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/astronomy/model4/zemlja/a_zemlja.gltf'),
      modelResourcesArr: [
        require('../models/astronomy/model4/zemlja/zemlja.bin'),
        require('../models/astronomy/model4/zemlja/Scene_-_Root_baseColor.jpg'),
      ],
    },
  ],
  botany: [
    {
      modelTitle: 'Tratinčica',
      modelLogo: require('../assets/modelImages/botany/model1/tratincicaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.005, // jel hocemo maleno da prostite?
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/botany/model1/tratincica/a_tratincica.gltf'),
      modelResourcesArr: [
        require('../models/botany/model1/tratincica/tratincica.bin'),
        require('../models/botany/model1/tratincica/Flower_baseColor.png'),
      ],
    },
    {
      modelTitle: 'Anturijum',
      modelLogo: require('../assets/modelImages/botany/model2/anturijumL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.15,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/botany/model2/flamingov_cvijet-anturijum/a_anturijum.gltf'),
      modelResourcesArr: [
        require('../models/botany/model2/flamingov_cvijet-anturijum/anturijum.bin'),
        require('../models/botany/model2/flamingov_cvijet-anturijum/Anthurium_final_baseColor.jpg'),
        require('../models/botany/model2/flamingov_cvijet-anturijum/Anthurium_final_metallicRoughness.png'),
        require('../models/botany/model2/flamingov_cvijet-anturijum/Anthurium_final_normal.png'),
      ],
    },
    {
      modelTitle: 'Mimoza',
      modelLogo: require('../assets/modelImages/botany/model3/mimozaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.3,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/botany/model3/mimoza/a_mimoza.gltf'),
      modelResourcesArr: [
        require('../models/botany/model3/mimoza/mimoza.bin'),
        require('../models/botany/model3/mimoza/Material__39.002_baseColor.png'),
        require('../models/botany/model3/mimoza/Material__40.002_baseColor.png'),
      ],
    },
    {
      modelTitle: 'Paprat',
      modelLogo: require('../assets/modelImages/botany/model4/papratL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.005,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/botany/model4/paprat/a_paprat.gltf'),
      modelResourcesArr: [
        require('../models/botany/model4/paprat/paprat.bin'),
        require('../models/botany/model4/paprat/lambert2SG_baseColor.png'),
        require('../models/botany/model4/paprat/lambert2SG_metallicRoughness.png'),
        require('../models/botany/model4/paprat/lambert2SG_normal.png'),
      ],
    },
  ],
  electronics: [
    {
      modelTitle: 'Matična ploča ASUS Z170-P',
      modelLogo: require('../assets/modelImages/electronics/model1/asusL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.05,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/electronics/model1/asusZ170-P/a_asus.gltf'),
      modelResourcesArr: [
        require('../models/electronics/model1/asusZ170-P/asus.bin'),
        require('../models/electronics/model1/asusZ170-P/Asus_Z170-P_Mobo_baseColor.jpg'),
        require('../models/electronics/model1/asusZ170-P/Asus_Z170-P_Mobo_metallicRoughness.png'),
        require('../models/electronics/model1/asusZ170-P/Asus_Z170-P_Mobo_normal.png'),
      ],
    },
    {
      modelTitle: 'RAM Crucial DDR4 16GB',
      modelLogo: require('../assets/modelImages/electronics/model2/ramL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0005,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/electronics/model2/RAM_Crucial_DDR4_16GB/a_ram.gltf'),
      modelResourcesArr: [
        require('../models/electronics/model2/RAM_Crucial_DDR4_16GB/ram.bin'),
        require('../models/electronics/model2/RAM_Crucial_DDR4_16GB/material_baseColor.png'),
        require('../models/electronics/model2/RAM_Crucial_DDR4_16GB/material_metallicRoughness.png'),
        require('../models/electronics/model2/RAM_Crucial_DDR4_16GB/material_normal.png'),
      ],
    },
    {
      modelTitle: 'Pentium Pro',
      modelLogo: require('../assets/modelImages/electronics/model3/pentium_proL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.01,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/electronics/model3/pentium_pro/a_pentium_pro.gltf'),
      modelResourcesArr: [
        require('../models/electronics/model3/pentium_pro/pentium_pro.bin'),
        require('../models/electronics/model3/pentium_pro/None_baseColor.png'),
      ],
    },
    {
      modelTitle: 'INTEL Celeron',
      modelLogo: require('../assets/modelImages/electronics/model4/intelL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.01,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/electronics/model4/INTELCeleron/a_intel.gltf'),
      modelResourcesArr: [
        require('../models/electronics/model4/INTELCeleron/intel.bin'),
        require('../models/electronics/model4/INTELCeleron/None_3543.png.7842_baseColor.png'),
      ],
    },
  ],
  chemistry: [
    {
      modelTitle: 'Glukoza',
      modelLogo: require('../assets/modelImages/chemistry/model1/glukozaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.03,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/chemistry/model1/glukozaC6H12O6/m_glukoza.gltf'),
      modelResourcesArr: [
        require('../models/chemistry/model1/glukozaC6H12O6/glukoza.bin'),
      ],
    },
    {
      modelTitle: 'Ugljen dioksid',
      modelLogo: require('../assets/modelImages/chemistry/model2/ugljendioksidL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/chemistry/model2/ugljendioksidCO2/m_ugljendioksid.gltf'),
      modelResourcesArr: [
        require('../models/chemistry/model2/ugljendioksidCO2/ugljendioksid.bin'),
      ],
      modelRotationArray: [0, 90, 0],
    },
    {
      modelTitle: 'Voda',
      modelLogo: require('../assets/modelImages/chemistry/model3/vodaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.05,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/chemistry/model3/vodaH20/m_voda.gltf'),
      modelResourcesArr: [
        require('../models/chemistry/model3/vodaH20/voda.bin'),
      ],
    },
    {
      modelTitle: 'Mliječna kiselina',
      modelLogo: require('../assets/modelImages/chemistry/model4/mlijecnakiselinaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0015,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/chemistry/model4/mlijecnakiselinaC3H6O3/m_kiselina.gltf'),
      modelResourcesArr: [
        require('../models/chemistry/model4/mlijecnakiselinaC3H6O3/kiselina.bin'),
      ],
    },
  ],
  // illusions: [
  //   {
  //     modelTitle: 'srce',
  //     modelLogo: require('../assets/modelImages/illusions/heartL.png'),
  //     modelImage:require('../assets/modelImages/anatomy/model1/cirozaL.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'bubreg',
  //     modelLogo: require('../assets/modelImages/illusions/kidneyL.png'),
  //     modelImage:require('../assets/modelImages/anatomy/model1/cirozaL.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'jetra',
  //     modelLogo: require('../assets/modelImages/illusions/liverL.png'),
  //     modelImage:require('../assets/modelImages/anatomy/model1/cirozaL.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'pluća',
  //     modelLogo: require('../assets/modelImages/illusions/lungsL.png'),
  //     modelImage:require('../assets/modelImages/anatomy/model1/cirozaL.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  // ],
  mycology: [
    {
      modelTitle: 'Muhara',
      modelLogo: require('../assets/modelImages/mycology/model1/muharaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0015,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/mycology/model1/muhara/a_muhara.gltf'),
      modelResourcesArr: [
        require('../models/mycology/model1/muhara/muhara.bin'),
        require('../models/mycology/model1/muhara/default_baseColor.png'),
        require('../models/mycology/model1/muhara/default_metallicRoughness.png'),
        require('../models/mycology/model1/muhara/default_normal.png'),
      ],
    },
    {
      modelTitle: 'Šitake',
      modelLogo: require('../assets/modelImages/mycology/model2/sitakeL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/mycology/model2/sitake_pecurka/a_sitake.gltf'),
      modelResourcesArr: [
        require('../models/mycology/model2/sitake_pecurka/sitake.bin'),
        require('../models/mycology/model2/sitake_pecurka/material0_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material1_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material2_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material3_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material4_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material5_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material6_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material7_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material8_baseColor.jpg'),
        require('../models/mycology/model2/sitake_pecurka/material9_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Sunčanica',
      modelLogo: require('../assets/modelImages/mycology/model3/suncanicaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0003,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/mycology/model3/suncanica/a_suncanica.gltf'),
      modelResourcesArr: [
        require('../models/mycology/model3/suncanica/suncanica.bin'),
        require('../models/mycology/model3/suncanica/Material0_baseColor.jpg'),
      ],
    },
    {
      modelTitle: 'Brezov ded',
      modelLogo: require('../assets/modelImages/mycology/model4/brezovdedL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.3,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/mycology/model4/brezov_ded/a_brezovded.gltf'),
      modelResourcesArr: [
        require('../models/mycology/model4/brezov_ded/brezovded.bin'),
        require('../models/mycology/model4/brezov_ded/Scene_-_Root_baseColor.png'),
        require('../models/mycology/model4/brezov_ded/Scene_-_Root_metallicRoughness.png'),
        require('../models/mycology/model4/brezov_ded/Scene_-_Root_normal.png'),
      ],
    },
  ],
  microbiology: [
    {
      modelTitle: 'Korona virus',
      modelLogo: require('../assets/modelImages/microbiology/model1/koronaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.2,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/microbiology/model1/korona_virus/a_korona.gltf'),
      modelResourcesArr: [
        require('../models/microbiology/model1/korona_virus/korona.bin'),
        require('../models/microbiology/model1/korona_virus/Parts_baseColor.png'),
        require('../models/microbiology/model1/korona_virus/SphereLow_baseColor.png'),
      ],
    },
    {
      modelTitle: 'Hepatitis B',
      modelLogo: require('../assets/modelImages/microbiology/model2/hepatitisL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0003,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/microbiology/model2/hepatitis_b/a_hepatitis.gltf'),
      modelResourcesArr: [
        require('../models/microbiology/model2/hepatitis_b/hepatitis.bin'),
        require('../models/microbiology/model2/hepatitis_b/Material_48_baseColor.jpg'),
        require('../models/microbiology/model2/hepatitis_b/Material_48_normal.png'),
        require('../models/microbiology/model2/hepatitis_b/Material_49_baseColor.jpg'),
        require('../models/microbiology/model2/hepatitis_b/Material_50_baseColor.jpg'),
        require('../models/microbiology/model2/hepatitis_b/Material_50_normal.png'),
        require('../models/microbiology/model2/hepatitis_b/Material_51_baseColor.jpg'),
        require('../models/microbiology/model2/hepatitis_b/Material_51_normal.png'),
      ],
    },
    {
      modelTitle: 'Eukariotska ćelija',
      modelLogo: require('../assets/modelImages/microbiology/model3/eukariotska_celijaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.02,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/microbiology/model3/eukariotska_celija/a_eukariotska_celija.gltf'),
      modelResourcesArr: [
        require('../models/microbiology/model3/eukariotska_celija/eukariotska_celija.bin'),
        require('../models/microbiology/model3/eukariotska_celija/envoltura1_baseColor.jpg'),
        require('../models/microbiology/model3/eukariotska_celija/envoltura1_normal.png'),
      ],
    },
    {
      modelTitle: 'DNK',
      modelLogo: require('../assets/modelImages/microbiology/model4/dnkL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.001,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/microbiology/model4/dnk/a_dnk.gltf'),
      modelResourcesArr: [
        require('../models/microbiology/model4/dnk/dnk.bin'),
        require('../models/microbiology/model4/dnk/Pairs_baseColor.png'),
      ],
    },
  ],
  zoology: [
    {
      modelTitle: 'Paun',
      modelLogo: require('../assets/modelImages/zoology/model1/paunL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.12,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/zoology/model1/paun/a_paun.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model1/paun/paun.bin'),
        require('../models/zoology/model1/paun/Paon_plumes_baseColor.png'),
        require('../models/zoology/model1/paun/Paon_baseColor.png'),
      ],
      modelRotationArray: [0, 80, 0],
    },
    {
      modelTitle: 'Tvor',
      modelLogo: require('../assets/modelImages/zoology/model2/tvorL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.12,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/zoology/model2/tvor/a_tvor.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model2/tvor/tvor.bin'),
        require('../models/zoology/model2/tvor/material_baseColor.png'),
      ],
      modelRotationArray: [0, -60, 0],
    },
    {
      modelTitle: 'Delfin',
      modelLogo: require('../assets/modelImages/zoology/model3/delfinL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.3,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/model3/delfin/a_delfin.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model3/delfin/delfin.bin'),
        require('../models/zoology/model3/delfin/lambert1_baseColor.png'),
        require('../models/zoology/model3/delfin/lambert1_metallicRoughness.png'),
        require('../models/zoology/model3/delfin/lambert1_normal.png'),
      ],
      modelRotationArray: [0, 90, 0],
    },
    {
      modelTitle: 'Komarac',
      modelLogo: require('../assets/modelImages/zoology/model4/komaracL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.05,
      shadowVisible: false,
      onGround: true, // hocemo li prikazivati na stolu ili stojeci
      modelSource: require('../models/zoology/model4/komarac/a_komarac.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model4/komarac/komarac.bin'),
        require('../models/zoology/model4/komarac/Material__0_baseColor.png'),
      ],
      modelRotationArray: [0, 90, 0],
    },
    {
      modelTitle: 'Morska kornjača',
      modelLogo: require('../assets/modelImages/zoology/model5/kornjacaL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.0015,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/model5/morska_kornjaca/a_kornjaca.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model5/morska_kornjaca/kornjaca.bin'),
        require('../models/zoology/model5/morska_kornjaca/material_0_baseColor.jpg'),
        require('../models/zoology/model5/morska_kornjaca/material_8_baseColor.jpg'),
      ],
      modelRotationArray: [0, 90, 0],
    },
    {
      modelTitle: 'Livadski puž',
      modelLogo: require('../assets/modelImages/zoology/model6/puzL.png'),
      modelImage: require('../assets/modelImages/anatomy/model1/cirozaL.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: true,
      modelSource: require('../models/zoology/model6/livadski_puz/a_puz.gltf'),
      modelResourcesArr: [
        require('../models/zoology/model6/livadski_puz/puz.bin'),
        require('../models/zoology/model6/livadski_puz/Shell_01_MAT_baseColor.png'),
        require('../models/zoology/model6/livadski_puz/Shell_01_MAT_metallicRoughness.png'),
        require('../models/zoology/model6/livadski_puz/Shell_01_MAT_normal.png'),
      ],
    },
  ],
};

// How to turn a list of object properties into an array
// https://stackoverflow.com/questions/46153975/using-flat-list-with-objectmap
