export default {
  anatomy: [
    {
      modelTitle: 'lav',
      modelLogo: require('../assets/modelImages/anatomy/heartL.png'),
      modelImage: require('../assets/modelPreviews/anatomy/heartP.png'),
      modelType: 'VRX',
      modelScale: 0.4,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/srce/heartVRX.vrx'),
      modelResourcesArr: [
        require('../models/anatomy/srce/left_atrium_diffuse.jpg'),
        require('../models/anatomy/srce/T_left_atrium_M.png'),
        require('../models/anatomy/srce/T_left_atrium_N.png'),
        require('../models/anatomy/srce/right_atrium_diffuse.jpg'),
        require('../models/anatomy/srce/T_right_atrium_M.png'),
        require('../models/anatomy/srce/T_right_atrium_N.png'),
        require('../models/anatomy/srce/Ventricles_diffuse.jpg'),
        require('../models/anatomy/srce/T_ventricles_M.png'),
        require('../models/anatomy/srce/T_ventricles_N.png'),
      ],
    },
    {
      modelTitle: 'mozak onaj model',
      modelLogo: require('../assets/modelImages/anatomy/kidneyL.png'),
      modelImage: require('../assets/modelPreviews/anatomy/kidneyP.png'),
      modelType: 'VRX',
      modelScale: 0.1,
      shadowVisible: false,
      onGround: false,
      modelSource: null,
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Jetra',
      modelLogo: require('../assets/modelImages/anatomy/liverL.png'),
      modelImage: require('../assets/modelPreviews/anatomy/liverP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/anatomy/jetra/jetra.gltf'),
      modelResourcesArr: [
        require('../models/anatomy/jetra/jetra.bin'),
        require('../models/anatomy/jetra/Material_baseColor.png'),
        require('../models/anatomy/jetra/Material_metallicRoughness.png'),
        require('../models/anatomy/jetra/Material_normal.png'),
        require('../models/anatomy/jetra/Material.011_normal.png'),
        require('../models/anatomy/jetra/Material.011_baseColor.png'),
        require('../models/anatomy/jetra/Material.012_normal.png'),
        require('../models/anatomy/jetra/Material.012_baseColor.png'),
        require('../models/anatomy/jetra/Material.012_metallicRoughness.png'),
        require('../models/anatomy/jetra/Material.013_normal.png'),
        require('../models/anatomy/jetra/Material.013_baseColor.png'),
        require('../models/anatomy/jetra/Material.013_metallicRoughness.png'),
        require('../models/anatomy/jetra/Material.015_normal.png'),
        require('../models/anatomy/jetra/Material.015_baseColor.png'),
        require('../models/anatomy/jetra/Material.015_metallicRoughness.png'),
      ],
    },
    {
      modelTitle: 'cvijet',
      modelLogo: require('../assets/modelImages/anatomy/lungsL.png'),
      modelImage: require('../assets/modelPreviews/anatomy/lungsP.png'),
      modelType: 'GLTF',
      modelScale: 0.1,
      shadowVisible: true,
      onGround: true,
      modelSource: require('../models/botany/flamingov_cvijet-anturijum/anturijum.gltf'),
      modelResourcesArr: [
        require('../models/botany/flamingov_cvijet-anturijum/anturijum.bin'),
      ],
    },
  ],
  astronomy: [
    {
      modelTitle: 'Zemlja',
      modelLogo: require('../assets/modelImages/astronomy/earthL.png'),
      modelImage: require('../assets/modelPreviews/astronomy/earthP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Mars',
      modelLogo: require('../assets/modelImages/astronomy/marsL.png'),
      modelImage: require('../assets/modelPreviews/astronomy/marsP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Mjesec',
      modelLogo: require('../assets/modelImages/astronomy/moonL.png'),
      modelImage: require('../assets/modelPreviews/astronomy/moonP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Sputnjik 1',
      modelLogo: require('../assets/modelImages/astronomy/sputnik1L.png'),
      modelImage: require('../assets/modelPreviews/astronomy/sputnik1P.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  botany: [
    {
      modelTitle: 'Anturijum',
      modelLogo: require('../assets/modelImages/botany/anturijumL.png'),
      modelImage: require('../assets/modelPreviews/botany/anturijumP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Dimak',
      modelLogo: require('../assets/modelImages/botany/dimakL.png'),
      modelImage: require('../assets/modelPreviews/botany/dimakP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Paprat',
      modelLogo: require('../assets/modelImages/botany/papratL.png'),
      modelImage: require('../assets/modelPreviews/botany/papratP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Tratinčica',
      modelLogo: require('../assets/modelImages/botany/tratincicaL.png'),
      modelImage: require('../assets/modelPreviews/botany/tratincicaP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  electronics: [
    {
      modelTitle: 'Matična ploča',
      modelLogo: require('../assets/modelImages/electronics/motherboardL.png'),
      modelImage: require('../assets/modelPreviews/electronics/motherboardP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Procesor',
      modelLogo: require('../assets/modelImages/electronics/processorL.png'),
      modelImage: require('../assets/modelPreviews/electronics/processorP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'RAM',
      modelLogo: require('../assets/modelImages/electronics/ramL.png'),
      modelImage: require('../assets/modelPreviews/electronics/ramP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Tranzistor',
      modelLogo: require('../assets/modelImages/electronics/transistorL.png'),
      modelImage: require('../assets/modelPreviews/electronics/transistorP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  chemistry: [
    {
      modelTitle: 'Ugljen-dioksid',
      modelLogo: require('../assets/modelImages/chemistry/carbon_dioxideL.png'),
      modelImage: require('../assets/modelPreviews/chemistry/carbon_dioxideP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Glukoza',
      modelLogo: require('../assets/modelImages/chemistry/glucosaL.png'),
      modelImage: require('../assets/modelPreviews/chemistry/glucosaP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Mliječna kiselina',
      modelLogo: require('../assets/modelImages/chemistry/milk_acidL.png'),
      modelImage: require('../assets/modelPreviews/chemistry/milk_acidP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Voda',
      modelLogo: require('../assets/modelImages/chemistry/waterL.png'),
      modelImage: require('../assets/modelPreviews/chemistry/waterP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  // illusions: [
  //   {
  //     modelTitle: 'srce',
  //     modelLogo: require('../assets/modelImages/illusions/heartL.png'),
  //     modelImage: require('../assets/modelPreviews/illusions/heartP.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'bubreg',
  //     modelLogo: require('../assets/modelImages/illusions/kidneyL.png'),
  //     modelImage: require('../assets/modelPreviews/illusions/kidneyP.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'jetra',
  //     modelLogo: require('../assets/modelImages/illusions/liverL.png'),
  //     modelImage: require('../assets/modelPreviews/illusions/liverP.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //
  //     modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  //   {
  //     modelTitle: 'pluća',
  //     modelLogo: require('../assets/modelImages/illusions/lungsL.png'),
  //     modelImage: require('../assets/modelPreviews/illusions/lungsP.png'),
  //     modelType: 'GLTF',
  //     modelScale: 0.5,
  //     shadowVisible: false,
  //     onGround: false,
  //
  modelSource: require('../models/zoology/lav/lav.gltf'),
  //     modelResourcesArr: [],
  //   },
  // ],
  mycology: [
    {
      modelTitle: 'Brazovded',
      modelLogo: require('../assets/modelImages/mycology/brazovdedL.png'),
      modelImage: require('../assets/modelPreviews/mycology/brazovdedP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Muhara',
      modelLogo: require('../assets/modelImages/mycology/muharaL.png'),
      modelImage: require('../assets/modelPreviews/mycology/muharaP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Šitake',
      modelLogo: require('../assets/modelImages/mycology/sitakeL.png'),
      modelImage: require('../assets/modelPreviews/mycology/sitakeP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Sunčanica',
      modelLogo: require('../assets/modelImages/mycology/suncanicaL.png'),
      modelImage: require('../assets/modelPreviews/mycology/suncanicaP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  microbiology: [
    {
      modelTitle: 'Ćelija',
      modelLogo: require('../assets/modelImages/microbiology/cellL.png'),
      modelImage: require('../assets/modelPreviews/microbiology/cellP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Covid-19',
      modelLogo: require('../assets/modelImages/microbiology/coronaL.png'),
      modelImage: require('../assets/modelPreviews/microbiology/coronaP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Hepatitis',
      modelLogo: require('../assets/modelImages/microbiology/hepatitisL.png'),
      modelImage: require('../assets/modelPreviews/microbiology/hepatitisP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Koža',
      modelLogo: require('../assets/modelImages/microbiology/skinL.png'),
      modelImage: require('../assets/modelPreviews/microbiology/skinP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
  zoology: [
    {
      modelTitle: 'Komarac',
      modelLogo: require('../assets/modelImages/zoology/mosquitoL.png'),
      modelImage: require('../assets/modelPreviews/zoology/mosquitoP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Pčela',
      modelLogo: require('../assets/modelImages/zoology/beeL.png'),
      modelImage: require('../assets/modelPreviews/zoology/beeP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Kornjača',
      modelLogo: require('../assets/modelImages/zoology/turtleL.png'),
      modelImage: require('../assets/modelPreviews/zoology/turtleP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Lav',
      modelLogo: require('../assets/modelImages/zoology/lionL.png'),
      modelImage: require('../assets/modelPreviews/zoology/lionP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Paun',
      modelLogo: require('../assets/modelImages/zoology/peacockL.png'),
      modelImage: require('../assets/modelPreviews/zoology/peacockP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
    {
      modelTitle: 'Puž',
      modelLogo: require('../assets/modelImages/zoology/snailL.png'),
      modelImage: require('../assets/modelPreviews/zoology/snailP.png'),
      modelType: 'GLTF',
      modelScale: 0.5,
      shadowVisible: false,
      onGround: false,
      modelSource: require('../models/zoology/lav/lav.gltf'),
      modelResourcesArr: [],
    },
  ],
};

// How to turn a list of object properties into an array
// https://stackoverflow.com/questions/46153975/using-flat-list-with-objectmap
